#!/bin/bash

### Below are directives which correspond to certain flags that are used by the PBS system
### All are prefixed with #PBS followed by the flag and the variable value
### An explanation of the use of the variables can be found 
### on github under the HPC-Basics directory titled "pbs-variables.pbs"

#PBS -N testing_R_array_job
#PBS -l select=1:ncpus=1:mem=1gb
#PBS -l walltime=01:00:00
#PBS -j oe
#PBS -J 1-3
#PBS -k oed
#PBS -M anthony.liu@student.unsw.edu.au
#PBS -m ae
#PBS -o /home/z5060070/testing/results/test_R_array_results

###---------------------------------------------------------------------------

### Below are the commands to set up the run environment for the program
### as well as the execution command itself

# Change to the directory the job was submitted from
cd $PBS_O_WORKDIR

# Load the desired R module and environment varables to be used 
module load R/3.6.1

# Command to run the job
Rscript R_array${PBS_ARRAY_INDEX}.R
